name: heat-analysis
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - fastapi=0.105.0
  - uvicorn=0.24.0
  - pandas=2.1.3
  - numpy=1.26.2
  - scipy=1.11.4
  - scikit-learn=1.3.2
  - matplotlib=3.8.2
  - tqdm=4.66.1
  - pytorch=2.1.1
